version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: minha_senha
      MYSQL_DATABASE: oficina_mecanica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
